site_name: KSKB-IX
theme:
  # name: material
  name: flatly
extra_css:
  - css/hidefooter.css
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.magiclink
nav:
  - KSKB-Net: index.md
  - Connection Infos: info.md
  - Looking Glass: lg.md
  - Poema Network: https://net.kskb.eu.org
site_url: https://dn42.kskb.eu.org/
repo_url: https://github.com/KSKBpage/dn42page
edit_uri: blob/main/docs/
